// Copyright 2022 Neeva Inc. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import Foundation

extension NSRegularExpression {
    fileprivate convenience init(_ pattern: String) {
        do {
            try self.init(pattern: pattern, options: [.anchorsMatchLines])
        } catch {
            preconditionFailure(
                "Illegal regular expression: \(pattern) \(error.localizedDescription)."
            )
        }
    }

    fileprivate static let percentEncodingMatcher = NSRegularExpression("(%[0-9a-fA-F]{2})")
}

extension String {
    fileprivate func trimmingPrefix<T: StringProtocol>(_ prefix: T) -> String {
        guard hasPrefix(prefix) else {
            return self
        }
        return String(dropFirst(prefix.count))
    }

    fileprivate func trimmingSuffix<T: StringProtocol>(_ suffix: T) -> String {
        guard hasSuffix(suffix) else {
            return self
        }
        return String(dropLast(suffix.count))
    }

    /// Convenience range object for using string with NSRegularExpression checkers
    fileprivate var fullRange: NSRange {
        NSRange(self.startIndex..., in: self)
    }

    fileprivate func replacingFirstOccurance<S: StringProtocol>(
        of element: S,
        with replacement: S
    ) -> String {
        guard let range = self.range(of: element) else {
            return self
        }
        return self.replacingCharacters(in: range, with: replacement)
    }

    fileprivate func lowercasedEscapingPercentEncoding() -> String {
        var currIdx = startIndex
        var resultString = ""

        NSRegularExpression.percentEncodingMatcher
            .enumerateMatches(in: self, range: fullRange) { result, _, _ in
                guard let result = result,
                    let range = Range(result.range, in: self)
                else {
                    return
                }
                defer { currIdx = range.upperBound }

                if currIdx < range.lowerBound {
                    // add non-percent encoded part
                    resultString += self[currIdx..<range.lowerBound].lowercased()
                }
                // use original case for percent encoded part
                resultString += self[range.lowerBound..<range.upperBound]
            }

        if currIdx < endIndex {
            resultString += self[currIdx..<endIndex].lowercased()
        }

        return resultString
    }
}

private enum Matchers {
    static let bestbuy = NSRegularExpression(#"/(?<productcode>[0-9]*)\.p$"#)
    static let cccAmazonProductMatcher = NSRegularExpression(#"/product/(?<productcode>\w*)"#)
    static let amazonPackageTracking = NSRegularExpression(#"/progress-tracker/package/"#)
    static let amazonIDFromReferral = NSRegularExpression(#"/g/r/.*/dp/(?<asin>\w*).*"#)
}

public struct CanonicalURL {
    private(set) var data: URLComponents

    public var asURL: URL? { data.url }

    public var asString: String? { data.string }

    public init?(from components: URLComponents, stripMobile: Bool = false, relaxed: Bool = false) {
        var components = components
        if stripMobile,
            let stripped = Self.stripMobile(url: components)
        {
            components = stripped
        }

        components = Self.canonicalize(components) ?? components

        if relaxed {
            Self.relax(url: &components)
        }
        self.data = components
    }

    public init?(from urlString: String, stripMobile: Bool = false, relaxed: Bool = false) {
        guard let components = URLComponents(string: urlString) else {
            return nil
        }

        self.init(from: components, stripMobile: stripMobile, relaxed: relaxed)
    }

    public init?(from url: URL, stripMobile: Bool = false, relaxed: Bool = false) {
        guard let components = URLComponents(url: url, resolvingAgainstBaseURL: true) else {
            return nil
        }

        self.init(from: components, stripMobile: stripMobile, relaxed: relaxed)
    }

    public static func stripMobile(url: URLComponents) -> URLComponents? {
        guard let string = url.string else {
            return nil
        }

        if string.contains("//m.") {
            return URLComponents(string: string.replacingFirstOccurance(of: "//m.", with: "//www."))
        } else if string.contains("//mobile.") {
            return URLComponents(
                string: string.replacingFirstOccurance(of: "//mobile.", with: "//www.")
            )
        } else if string.contains(".m.wiki") {
            return URLComponents(
                string: string.replacingFirstOccurance(of: ".m.wiki", with: ".wiki")
            )
        }

        return url
    }

    /// Port of CanonicalURLV3
    ///
    /// Notes when porting from Golang:
    /// - In Go, query, path, fragment, etc. are cleared by assigning empty string; in Swift, `nil` should be assigned
    /// - `URLComponents.queryItems` needs to be set to `nil` instead of `[]` to remove trailing `?`
    /// - In Go, `url.URL.RawQuery = url.URL.Query().Encode()`sorts the query by key; Swift encodes `URLComponents.queryItems` in the order of the array
    /// - `URLComponents.path` argument needs to start with `/`. See `path` documentation for more details
    /// - In Go, regexp matcher returns match and subgroup match in one array; in swift, they are contained within each `NSTextCheckingResult` object
    /// - In Go, strings.Split() is equivalent to `String.split(separator:, omittingEmptySubsequences: false)` in Swift
    /// - Go always operate on percent encoded URLs; `percentEncoded<>` properties need to be explicitly used to retain these symbols
    /// - In Go, url.Parse can parse urls with ":/" percent encoded; swift cannot. This results in a modified approach for best buy redirects
    /// - In Go, strings.ToLower() escapes percent encoding symbols. Swift `String.lowercased()` does not
    private static func canonicalize(_ urlComponents: URLComponents) -> URLComponents? {
        let inputString = urlComponents.string

        var components = urlComponents
        canonicalizeWirecutter(url: &components)

        components.percentEncodedHost = components.percentEncodedHost?.lowercased()
        components.fragment = nil

        switch components.host {
        case "assoc-redirect.amazon.com":
            let path = components.percentEncodedPath
            let matches = Matchers.amazonIDFromReferral.matches(in: path, range: path.fullRange)
            if let result = matches.first,
                let extractedRange = Range(result.range(withName: "asin"), in: path)
            {
                components.host = "www.amazon.com"
                components.percentEncodedPath = "/dp/" + String(path[extractedRange])
                components.query = nil
            }
        case "www.amazon.com":
            if let range = components.percentEncodedPath.range(of: "/ref=", options: [.backwards]),
                range.lowerBound >= components.percentEncodedPath.startIndex,
                !range.isEmpty
            {
                if let string = inputString,
                    Matchers.amazonPackageTracking.firstMatch(in: string, range: string.fullRange)
                        != nil
                {
                    return nil
                }
                components.percentEncodedPath = String(
                    components.percentEncodedPath[..<range.lowerBound]
                )
            }

            let parts = components.percentEncodedPath.split(
                separator: "/", omittingEmptySubsequences: false)
            if parts.count == 4, parts[2] == "dp" {
                components.percentEncodedPath = "/dp/" + parts[3]
            } else if parts.count == 4, parts[1] == "gp" {
                components.percentEncodedPath = "/dp/" + parts[3]
            } else if parts.count == 3, parts[2] == "s" {
                components.percentEncodedPath = "/s"
            }

            let allowedParams = Set([
                "docId", "id", "k", "me", "messageID", "node", "nodeId", "seller", "srs",
                "threadID", "rh", "zipcode",
            ])
            let filterFunc: (URLQueryItem) -> Bool = { item in
                guard let value = item.value, !value.isEmpty else {
                    return false
                }
                if allowedParams.contains(item.name) {
                    return true
                }
                if item.name == "pg",
                    value != "1"
                {
                    return true
                }
                return false
            }
            if let filteredQueryItems = components.percentEncodedQueryItems?.filter(filterFunc)
                .sorted(by: { $0.name < $1.name })
            {
                components.percentEncodedQueryItems =
                    filteredQueryItems.isEmpty ? nil : filteredQueryItems
            }
        case "bestbuy.7tiv.net":
            let queryItems = components.percentEncodedQueryItems
            if let skuItem = queryItems?.first(where: { $0.name == "prodsku" }) {
                if let sku = skuItem.value, !sku.isEmpty {
                    components.host = "www.bestbuy.com"
                    components.percentEncodedPath = "/site/" + sku + ".p"
                    components.query = nil
                }
            } else if let redirectItem = queryItems?.first(where: { $0.name == "u" }),
                let redirect = redirectItem.value?.removingPercentEncoding,
                !redirect.isEmpty
            {
                guard let redirectURL = URLComponents(string: redirect) else {
                    return nil
                }
                components = redirectURL
                if components.host == "www.bestbuy.com" {
                    let path = components.percentEncodedPath
                    let matches = Matchers.bestbuy.matches(in: path, range: path.fullRange)
                    if let result = matches.first,
                        let extractedRange = Range(result.range(withName: "productcode"), in: path)
                    {
                        components.percentEncodedPath =
                            "/site/" + String(path[extractedRange]) + ".p"
                        components.query = nil
                    }
                }
            }
        case "www.bestbuy.com":
            let path = components.percentEncodedPath
            let matches = Matchers.bestbuy.matches(in: path, range: path.fullRange)
            if let result = matches.first,
                let extractedRange = Range(result.range(withName: "productcode"), in: path)
            {
                components.percentEncodedPath = "/site/" + String(path[extractedRange]) + ".p"
                components.query = nil
            }
        case "camelcamelcamel.com", "www.camelcamelcamel.com":
            let path = components.percentEncodedPath
            let matches = Matchers.cccAmazonProductMatcher.matches(in: path, range: path.fullRange)
            if let result = matches.first,
                let extractedRange = Range(result.range(withName: "productcode"), in: path)
            {
                components.percentEncodedPath = "/product/" + String(path[extractedRange])
                components.query = nil
            }
        case "www.target.com":
            let parts = components.percentEncodedPath.split(
                separator: "/",
                omittingEmptySubsequences: false
            )
            if parts.count == 4, parts[1] == "p", parts[2] == "-" {
                components.percentEncodedPath = "/p/-/" + parts[3]
                components.query = nil
            } else if parts.count == 5, parts[1] == "p", parts[3] == "-" {
                components.percentEncodedPath = "/p/-/" + parts[4]
                components.query = nil
            }
        case "www.walmart.com":
            let parts = components.percentEncodedPath.split(
                separator: "/",
                omittingEmptySubsequences: false
            )
            if parts.count == 4, parts[1] == "ip" {
                components.percentEncodedPath = "/ip/" + parts[3]
                components.query = nil
            }
        case "www.homedepot.com":
            if components.percentEncodedPath.hasPrefix("/p") {
                components.query = nil
            }
        default:
            if let host = components.host,
                stackExchangeHosts.contains(host)
            {
                let parts = components.percentEncodedPath.split(
                    separator: "/",
                    omittingEmptySubsequences: false
                )
                if parts.count == 4, parts[1] == "questions", parts[2] != "tagged" {
                    components.percentEncodedPath = parts[0..<3].joined(separator: "/")
                } else if parts.count == 5, parts[1] == "questions", parts[4] == "" {
                    components.percentEncodedPath = parts[0..<3].joined(separator: "/")
                }
            }
        }

        components.scheme = "https"
        if let host = components.host,
            !domainToNotStripSlash.contains(host.trimmingPrefix("www."))
        {
            components.percentEncodedPath = components.percentEncodedPath.trimmingSuffix("/")
        }

        components = strippingQueryParam(from: components)

        // V3
        if let host = components.host {
            var trimmedHost = host.trimmingPrefix("www.")
            if trimmedHost == host {
                trimmedHost = host.trimmingPrefix("www1.")
            }
            if domainToStripWWW.contains(trimmedHost) {
                components.host = trimmedHost
            }
            if domainToLowerPath.contains(trimmedHost) {
                let loweredPath = components.percentEncodedPath.lowercasedEscapingPercentEncoding()
                components.percentEncodedPath = loweredPath
            }
        }

        if let host = components.host,
            stackExchangeHosts.contains(host)
        {
            var parts = components.percentEncodedPath.split(
                separator: "/",
                omittingEmptySubsequences: false
            )
            if parts.count == 5, parts[1] == "questions", parts[2] != "tagged" {
                components.percentEncodedPath = parts[0..<3].joined(separator: "/")
            } else if parts.count == 4 || parts.count == 5, parts[1] == "q" {
                parts[1] = "questions"
                components.percentEncodedPath = parts[0..<3].joined(separator: "/")
            }
        }

        if components.host == "www.amazon.com" {
            let allowedParams = Set([
                "docId", "id", "k", "me", "messageID", "node", "nodeId", "seller", "srs",
                "threadID", "rh", "zipcode",
            ])
            let transformFunc: (URLQueryItem) -> URLQueryItem? = { item in
                if allowedParams.contains(item.name),
                    let value = item.value,
                    !value.isEmpty
                {
                    let loweredValue = value.lowercasedEscapingPercentEncoding()
                    return URLQueryItem(name: item.name, value: loweredValue)
                }
                if item.name == "pg",
                    let value = item.value,
                    !value.isEmpty,
                    value != "1"
                {
                    let loweredValue = value.lowercasedEscapingPercentEncoding()
                    return URLQueryItem(name: item.name, value: loweredValue)
                }
                return nil
            }
            let transformedQueryItems = components.percentEncodedQueryItems?
                .compactMap(transformFunc)
                .sorted(by: { $0.name < $1.name })
            if let transformedQueryItems = transformedQueryItems {
                components.percentEncodedQueryItems =
                    transformedQueryItems.isEmpty ? nil : transformedQueryItems
            }
        }

        return components
    }

    private static func relax(url components: inout URLComponents) {
        components.percentEncodedHost = components.percentEncodedHost?.trimmingPrefix("www.")
        components.percentEncodedHost = components.percentEncodedHost?.trimmingPrefix("www1.")
        components.percentEncodedPath = components.percentEncodedPath
            .lowercasedEscapingPercentEncoding()

        canonicalizeGolangPackages(url: &components)

        // url.Query().Encode() sorts the query params
        components.percentEncodedQueryItems = components.percentEncodedQueryItems?.sorted(by: {
            $0.name < $1.name
        })
    }

    /// Named `canonicalizeGolangPackages` in Go
    private static func canonicalizeGolangPackages(url components: inout URLComponents) {
        guard ["golang.org", "godoc.org"].contains(components.host) else {
            return
        }
        components.host = "pkg.go.dev"
        components.percentEncodedPath = components.percentEncodedPath.trimmingPrefix("/pkg")
    }

    /// Named `wirecutterToNYTimes` in Go
    private static func canonicalizeWirecutter(url components: inout URLComponents) {
        let prefixes: Set<String> = [
            "wirecutter.com", "www.wirecutter.com", "thewirecutter.com", "www.thewirecutter.com",
        ]
        guard let host = components.percentEncodedHost ?? components.host,
            !prefixes.filter({ host.hasPrefix($0) }).isEmpty
        else {
            return
        }

        components.host = "www.nytimes.com"
        components.percentEncodedPath = "/wirecutter" + components.percentEncodedPath

        return
    }

    private static func strippingQueryParam(from components: URLComponents) -> URLComponents {
        guard let host = components.host,
            let queryParamSet = domainToKeepQueryParam[host.trimmingPrefix("www.")]
        else {
            return components
        }

        var result = components

        if let filteredQueryItems = components.percentEncodedQueryItems?
            .filter({ queryParamSet.contains($0.name) })
            .sorted(by: { $0.name < $1.name })
        {
            result.percentEncodedQueryItems = filteredQueryItems.isEmpty ? nil : filteredQueryItems
        }

        return result
    }

    private static let domainToNotStripSlash: Set<String> = [
        "asos.com",
        "revolve.com",
        "westelmn.com",
    ]

    private static let domainToKeepQueryParam: [String: Set<String>] = [
        "abt.com": [],
        "apple.com": ["device1", "device2", "device3", "modelList"],
        "ashleyfurniture.com": [],
        "ballarddesigns": [],
        "bedbathandbeyond.com": [],
        "biglots.com": [],
        "bloomingdales.com": ["id"],
        "bombas.com": [],
        "brooksbrothers.com": [],
        "buybuybaby.com": [],
        "calvinklein.us": [],
        "coach.com": [],
        "columbia.com": [],
        "converse.com": [],
        "dell.com": ["driverid"],
        "etsy.com": ["q"],
        "finishline.com": ["styleId", "colorId"],
        "forever21.com": ["br21"],
        "frontgate.com": [],
        "godoc.org": [],
        "golang.org": [],
        "goodreads.com": ["shelf", "page", "view"],
        "jcrew.com": ["brand", "color", "discount", "fit", "size"],
        "katespade.com": [],
        "luckybrand.com": [],
        "mackage.com": [],
        "macys.com": ["ID", "id"],
        "madewell.com": [],
        "michaelkors.com": [],
        "mytheresa.com": [],
        "newbalance.com": [],
        "nordstrom.com": [],
        "onekingslane.com": [],
        "pacsun.com": [],
        "patagonia.com": ["productid"],
        "pkg.go.dev": [],
        "poshmark.com": [],
        "potterybarn.com": ["words"],
        "potterybarnkids.com": ["words"],
        "ralphlauren.com": [],
        "rei.com": [],
        "saksfifthavenue.com": [],
        "saksoff5th.com": [],
        "sephora.com": [],
        "shopbop.com": [],
        "staples.com": [],
        "talbots.com": [],
        "thecompanystore.com": [],
        "ulta.com": ["productId"],
        "underarmour.com": [],
        "us.jimmychoo.com": [],
        "us.puma.com": [],
        "vince.com": [],
        "wayfair.com": ["goto", "keyword"],
        "westelm.com": ["words"],
        "worldmarket.com": [],
        "ysl.com": [],
    ]

    private static let stackExchangeHosts: Set<String> = [
        "3dprinting.stackexchange.com",
        "academia.stackexchange.com",
        "ai.stackexchange.com",
        "android.stackexchange.com",
        "anime.stackexchange.com",
        "apple.stackexchange.com",
        "arduino.stackexchange.com",
        "askubuntu.com",
        "astronomy.stackexchange.com",
        "aviation.stackexchange.com",
        "avp.stackexchange.com",
        "beer.stackexchange.com",
        "bicycles.stackexchange.com",
        "bioinformatics.stackexchange.com",
        "biology.stackexchange.com",
        "bitcoin.stackexchange.com",
        "blender.stackexchange.com",
        "boardgames.stackexchange.com",
        "bricks.stackexchange.com",
        "buddhism.stackexchange.com",
        "chemistry.stackexchange.com",
        "chess.stackexchange.com",
        "chinese.stackexchange.com",
        "christianity.stackexchange.com",
        "civicrm.stackexchange.com",
        "codegolf.stackexchange.com",
        "codereview.stackexchange.com",
        "coffee.stackexchange.com",
        "cogsci.stackexchange.com",
        "computergraphics.stackexchange.com",
        "conlang.stackexchange.com",
        "cooking.stackexchange.com",
        "craftcms.stackexchange.com",
        "crafts.stackexchange.com",
        "crypto.stackexchange.com",
        "cs.stackexchange.com",
        "cseducators.stackexchange.com",
        "cstheory.stackexchange.com",
        "datascience.stackexchange.com",
        "dba.stackexchange.com",
        "devops.stackexchange.com",
        "diy.stackexchange.com",
        "drupal.stackexchange.com",
        "dsp.stackexchange.com",
        "earthscience.stackexchange.com",
        "ebooks.stackexchange.com",
        "economics.stackexchange.com",
        "electronics.stackexchange.com",
        "elementaryos.stackexchange.com",
        "ell.stackexchange.com",
        "emacs.stackexchange.com",
        "engineering.stackexchange.com",
        "english.stackexchange.com",
        "eosio.stackexchange.com",
        "es.stackoverflow.com",
        "esperanto.stackexchange.com",
        "ethereum.stackexchange.com",
        "expatriates.stackexchange.com",
        "expressionengine.stackexchange.com",
        "fitness.stackexchange.com",
        "freelancing.stackexchange.com",
        "french.stackexchange.com",
        "gamedev.stackexchange.com",
        "gaming.stackexchange.com",
        "gardening.stackexchange.com",
        "genealogy.stackexchange.com",
        "german.stackexchange.com",
        "gis.stackexchange.com",
        "graphicdesign.stackexchange.com",
        "ham.stackexchange.com",
        "hardwarerecs.stackexchange.com",
        "health.stackexchange.com",
        "hermeneutics.stackexchange.com",
        "hinduism.stackexchange.com",
        "history.stackexchange.com",
        "homebrew.stackexchange.com",
        "hsm.stackexchange.com",
        "interpersonal.stackexchange.com",
        "iot.stackexchange.com",
        "iota.stackexchange.com",
        "islam.stackexchange.com",
        "italian.stackexchange.com",
        "ja.stackoverflow.com",
        "japanese.stackexchange.com",
        "joomla.stackexchange.com",
        "judaism.stackexchange.com",
        "korean.stackexchange.com",
        "languagelearning.stackexchange.com",
        "latin.stackexchange.com",
        "law.stackexchange.com",
        "lifehacks.stackexchange.com",
        "linguistics.stackexchange.com",
        "literature.stackexchange.com",
        "magento.stackexchange.com",
        "martialarts.stackexchange.com",
        "math.stackexchange.com",
        "matheducators.stackexchange.com",
        "mathematica.stackexchange.com",
        "mathoverflow.net",
        "mechanics.stackexchange.com",
        "moderators.stackexchange.com",
        "monero.stackexchange.com",
        "money.stackexchange.com",
        "movies.stackexchange.com",
        "music.stackexchange.com",
        "musicfans.stackexchange.com",
        "mythology.stackexchange.com",
        "networkengineering.stackexchange.com",
        "opendata.stackexchange.com",
        "opensource.stackexchange.com",
        "or.stackexchange.com",
        "outdoors.stackexchange.com",
        "parenting.stackexchange.com",
        "patents.stackexchange.com",
        "pets.stackexchange.com",
        "philosophy.stackexchange.com",
        "photo.stackexchange.com",
        "physics.stackexchange.com",
        "pm.stackexchange.com",
        "poker.stackexchange.com",
        "politics.stackexchange.com",
        "portuguese.stackexchange.com",
        "pt.stackoverflow.com",
        "puzzling.stackexchange.com",
        "quant.stackexchange.com",
        "quantumcomputing.stackexchange.com",
        "raspberrypi.stackexchange.com",
        "retrocomputing.stackexchange.com",
        "reverseengineering.stackexchange.com",
        "robotics.stackexchange.com",
        "rpg.stackexchange.com",
        "ru.stackoverflow.com",
        "rus.stackexchange.com",
        "russian.stackexchange.com",
        "salesforce.stackexchange.com",
        "scicomp.stackexchange.com",
        "scifi.stackexchange.com",
        "security.stackexchange.com",
        "serverfault.com",
        "sharepoint.stackexchange.com",
        "sitecore.stackexchange.com",
        "skeptics.stackexchange.com",
        "softwareengineering.stackexchange.com",
        "softwarerecs.stackexchange.com",
        "sound.stackexchange.com",
        "space.stackexchange.com",
        "spanish.stackexchange.com",
        "sports.stackexchange.com",
        "sqa.stackexchange.com",
        "stackapps.com",
        "stackoverflow.com",
        "stats.stackexchange.com",
        "stellar.stackexchange.com",
        "superuser.com",
        "sustainability.stackexchange.com",
        "tex.stackexchange.com",
        "tezos.stackexchange.com",
        "tor.stackexchange.com",
        "travel.stackexchange.com",
        "tridion.stackexchange.com",
        "ukrainian.stackexchange.com",
        "unix.stackexchange.com",
        "ux.stackexchange.com",
        "vegetarianism.stackexchange.com",
        "vi.stackexchange.com",
        "webapps.stackexchange.com",
        "webmasters.stackexchange.com",
        "windowsphone.stackexchange.com",
        "woodworking.stackexchange.com",
        "wordpress.stackexchange.com",
        "workplace.stackexchange.com",
        "worldbuilding.stackexchange.com",
        "writers.stackexchange.com",
    ]

    private static let domainToStripWWW: Set<String> = [
        "0x65.dev",
        "1040.com",
        "3480-3590-data-conversion.com",
        "4bes.nl",
        "599cd.com",
        "7-zip.org",
        "aaai.org",
        "accessibilityresources.org",
        "activatejavascript.org",
        "addall.com",
        "adilapapaya.com",
        "adoodle.org",
        "adventureworks.org",
        "advertisingview.com",
        "afb.org",
        "aggregate.org",
        "agiledata.org",
        "agilemodeling.com",
        "agiliq.com",
        "ai-startups.org",
        "aidanhogan.com",
        "aishack.in",
        "algostructure.com",
        "allhotkeys.com",
        "allmenus.com",
        "alpinelinux.org",
        "amazon.jobs",
        "ammyy.com",
        "ampsoft.net",
        "amundsen.com",
        "andrewberls.com",
        "angusj.com",
        "annaporterartist.com",
        "any-video-converter.com",
        "aonprd.com",
        "aosabook.org",
        "apache.org",
        "api-data.com",
        "applian.com",
        "applied-survey-methods.com",
        "apycom.com",
        "archive.org",
        "archiveofourown.org",
        "arothuis.nl",
        "asawicki.info",
        "asi-ware.com",
        "asicguru.com",
        "audd.io",
        "audiosciencereview.com",
        "audioxpress.com",
        "austinrochford.com",
        "austintexas.gov",
        "autoclicker.cc",
        "avajava.com",
        "avi-writer.com",
        "avlusa.com",
        "azuredevopslabs.com",
        "babelstone.co.uk",
        "babynames.com",
        "ballotpedia.org",
        "basicagency.com",
        "bbeditextras.org",
        "beach.io",
        "beginnerjavascript.com",
        "bernardmarr.com",
        "beyondcorp.com",
        "beyondlogic.org",
        "biblehub.com",
        "bieglercpa.com",
        "bing.com",
        "biostat.wisc.edu",
        "bits-pilani.ac.in",
        "blendermarket.com",
        "blog.ezekielekunola.com",
        "blog.google",
        "blooberry.com",
        "bluecrossnc.com",
        "bmdynamics.com",
        "boardgamegeek.com",
        "bogotobogo.com",
        "boldcontrol.com",
        "bostongis.com",
        "branchci.com",
        "brandnewbox.com",
        "brendanfong.com",
        "brendangregg.com",
        "brennan.id.au",
        "brinckerhoff.org",
        "browser-update.org",
        "browsersync.io",
        "btechsmartclass.com",
        "btobconnect.com",
        "business.gov.au",
        "busybox.net",
        "bytedude.com",
        "cairographics.org",
        "calculator.com",
        "caniuse.com",
        "careercup.com",
        "casectrl.com",
        "catb.org",
        "caveofprogramming.com",
        "cbs58.com",
        "cburch.com",
        "ccasantafe.org",
        "cesium.com",
        "cfn.upenn.edu",
        "chapsas.com",
        "charbase.com",
        "cheatengine.org",
        "chercher.tech",
        "chocolatey.org",
        "chrisnicoll.net",
        "christoolivier.com",
        "chromestatus.com",
        "cinemark.com",
        "citibank.co.uk",
        "classdojo.com",
        "classicperform.com",
        "classicshell.net",
        "claudiajs.com",
        "clinicaltrials.gov",
        "cliqz.com",
        "clojure.org",
        "cmmiinstitute.com",
        "cobbaut.be",
        "cocoadevcentral.com",
        "codecguide.com",
        "codeinwp.com",
        "codemoji.com",
        "codenames.plus",
        "coderanch.com",
        "coderrocketfuel.com",
        "codinghelmet.com",
        "codingsans.com",
        "cohascodpc.com",
        "coinranking.com",
        "colchesterdigital.org.uk",
        "coletiv.com",
        "color-ize.com",
        "colormatters.com",
        "community.spiceworks.com",
        "compose.com",
        "computersciencewiki.org",
        "comscigate.com",
        "configcat.com",
        "connectnc.com",
        "consultesoft.com",
        "contactout.com",
        "contextures.com",
        "controlflow.com",
        "convert-units.info",
        "converteverything.com",
        "convertstring.com",
        "cookbook-r.com",
        "copymydata.com",
        "corelangs.com",
        "coronavirus.in.gov",
        "cosinekitty.com",
        "countrycode.org",
        "coursescript.com",
        "cplusplus.com",
        "cpp.sh",
        "crunchbase.com",
        "cryptologie.net",
        "cryptomuseum.com",
        "cs-fundamentals.com",
        "cs.auckland.ac.nz",
        "cs.colby.edu",
        "cs.dartmouth.edu",
        "cs.ioc.ee",
        "cs.jhu.edu",
        "cs.rochester.edu",
        "csci.csusb.edu",
        "cse.buffalo.edu",
        "csit-sun.pub.ro",
        "css-infos.net",
        "cssanalyzer.com",
        "cssmine.com",
        "cssportal.com",
        "ctan.org",
        "ctimls.com",
        "cvshealth.com",
        "cybercircuits.co.nz",
        "cyberdriveillinois.com",
        "dagster.io",
        "danorlovsky.tech",
        "datafordemocracy.org",
        "datagenetics.com",
        "datatables.net",
        "davidmlane.com",
        "davidokwii.com",
        "davidsottimano.com",
        "dba-oracle.com",
        "dbvis.com",
        "deadlybossmods.com",
        "debuggable.com",
        "debuggex.com",
        "december.com",
        "dejazzer.com",
        "delimitware.com",
        "delphic.me.uk",
        "derekgourlay.com",
        "dermnetnz.org",
        "designcise.com",
        "developer.amazon.com",
        "dir.ca.gov",
        "discourse.org",
        "dkim.org",
        "docs.opencv.org",
        "dofactory.com",
        "doordashstore.com",
        "dos.myflorida.com",
        "doyourownpestcontrol.com",
        "dph.illinois.gov",
        "dpriver.com",
        "drububu.com",
        "ds100.org",
        "dshs.texas.gov",
        "dualwriter.com",
        "dyn-web.com",
        "easy-tensorflow.com",
        "ec2instances.info",
        "echoecho.com",
        "ecma-international.org",
        "economics.emory.edu",
        "economics.utoronto.ca",
        "ecpannualmeeting.com",
        "edd.ca.gov",
        "edwardthomson.com",
        "effbot.org",
        "eksworkshop.com",
        "elinux.org",
        "emailaddressmanager.com",
        "enable-javascript.com",
        "encorebusiness.com",
        "endmemo.com",
        "enlp.eu.com",
        "eprosima.com",
        "epubor.com",
        "erg.abdn.ac.uk",
        "essenceglobal.com",
        "eventhelix.com",
        "evermap.com",
        "everythingcomputerscience.com",
        "exifdata.com",
        "exiftool.org",
        "expressflow.com",
        "expressionsstores.com",
        "extracttable.com",
        "ezfn.dev",
        "facebook.design",
        "farazpatankar.com",
        "favorites-menu.com",
        "festi.info",
        "filesmerge.com",
        "fintechweekly.com",
        "finviz.com",
        "firehydrant.io",
        "fivestars.blog",
        "fixyourownprinter.com",
        "flagguys.com",
        "flalottery.com",
        "flathub.org",
        "flatpak.org",
        "fleethub.shell.com",
        "flightclub.com",
        "floydhilton.com",
        "fofxacademy.com",
        "fontawesome.cc",
        "fraudaid.com",
        "freedesktop.org",
        "freeonlineflashlight.com",
        "freepdfconvert.com",
        "freertos.org",
        "freeviewnz.tv",
        "fromtexttospeech.com",
        "frontline.vc",
        "fueleconomy.gov",
        "fullpagescreencapture.com",
        "fws.gov",
        "gaijin.at",
        "game-debate.com",
        "gamersdecide.com",
        "gammon.com.au",
        "gcaltoolkit.com",
        "gdeepak.com",
        "geocene.com",
        "geoffchappell.com",
        "geomidpoint.com",
        "getadblock.com",
        "gettheburger.com",
        "getyarn.io",
        "ghostscript.com",
        "ginifab.com",
        "git-scm.com",
        "github.com",
        "gitj.com",
        "gitmemory.com",
        "gjermundbjaanes.com",
        "glmoperations.com",
        "gmail.com",
        "gnupg.org",
        "godoc.org",
        "goer.org",
        "gofullbuild.com",
        "goldensoft.org",
        "golinks.io",
        "gonetspeed.com",
        "goofle.com",
        "google.com",
        "google.org",
        "gotthelook.com",
        "gradient.com",
        "gradschool.fsu.edu",
        "grow.google",
        "grpc.io",
        "gruntwork.io",
        "grymoire.com",
        "gsuite.google.com",
        "gsw.edu",
        "gtcc.edu",
        "guidgenerator.com",
        "gutenberg.org",
        "gzip.org",
        "hackernoon.com",
        "hanab.live",
        "handholdreport.com",
        "happyzebra.com",
        "harborfreight.com",
        "haselt.com",
        "hashtagopen.com",
        "haynerlibrary.org",
        "hdrhistogram.org",
        "hdtuto.com",
        "healow.com",
        "healthychildren.org",
        "helenanderson.co.nz",
        "hex2rgba.devoth.com",
        "hexus.net",
        "hl7.org",
        "honorless.net",
        "htmlandcssbook.com",
        "htmldog.com",
        "htmlescape.net",
        "htmlhelp.com",
        "hyperlinkcode.com",
        "ibo.org",
        "iconarchive.com",
        "ics.forth.gr",
        "ideone.com",
        "ieee802.org",
        "ietf.org",
        "igniterealtime.org",
        "igs.berkeley.edu",
        "ilga.gov",
        "illinoiswildflowers.info",
        "imageai.org",
        "imei24.com",
        "imeipro.info",
        "immixgroup.com",
        "immunize.org",
        "included.vc",
        "infinityworks.com",
        "informationisbeautiful.net",
        "informationweek.com",
        "interactivebrokers.com",
        "internettrafficreport.com",
        "invoice.land",
        "iosrjen.org",
        "ipadacademy.com",
        "ipaddressguide.com",
        "iphoneresolution.com",
        "iremover.org",
        "ironspider.ca",
        "ishadeed.com",
        "iterm2.com",
        "itl.nist.gov",
        "iunlocker.com",
        "java.com",
        "java2novice.com",
        "javascripter.net",
        "javascriptkit.com",
        "jayconrod.com",
        "jazkarta.com",
        "jdash.io",
        "jekyll.math.byuh.edu",
        "jkorpela.fi",
        "jmlr.org",
        "jnis.ac.in",
        "jochenhebbrecht.be",
        "joshwcomeau.com",
        "jrgraphix.net",
        "json.org",
        "jsondiff.com",
        "jsonrpc.org",
        "jsonschema.net",
        "juliaobserver.com",
        "jxplorer.org",
        "kalmstrom.com",
        "katacoda.com",
        "kbdedit.com",
        "keefegroup.com",
        "kenrockwell.com",
        "key.me",
        "keybr.com",
        "keyxl.com",
        "khou.com",
        "khronos.org",
        "kidsmathgamesonline.com",
        "kimsereylam.com",
        "kingcounty.gov",
        "kirenz.com",
        "kite.com",
        "kodlogs.com",
        "kuow.org",
        "kvance.com",
        "kwcontrolpanel.com",
        "kyjustice.org",
        "lab.dotjay.com",
        "labs.ovh.com",
        "labservices.com",
        "lakesnwoods.com",
        "laserscanningforum.com",
        "latex-cookbook.net",
        "lazesoft.com",
        "ldapbrowsermac.com",
        "learnabout-electronics.org",
        "learnersdictionary.com",
        "learnyouahaskell.com",
        "lethain.com",
        "lexjansen.com",
        "linear.app",
        "linkedbuildingdata.net",
        "linux-sxs.org",
        "linuxcertified.com",
        "linuxcommand.org",
        "linuxconsultant.info",
        "linuxmint.com",
        "llvm.org",
        "loadsystems.co.uk",
        "lockheedmartin.com",
        "login.gov",
        "louisiana.edu",
        "lsu.edu",
        "lucenetutorial.com",
        "lukasa.co.uk",
        "lzone.de",
        "m2mate.com",
        "m3db.io",
        "m4vgear.com",
        "machenxiao.com",
        "macsx.com",
        "madebyevan.com",
        "magnum.graphics",
        "man7.org",
        "mangolassi.it",
        "manuelmeyer.net",
        "mapleprimes.com",
        "markdownpad.com",
        "marmalade-repo.org",
        "martinfowler.com",
        "marvelousdesigner.com",
        "masteringemacs.org",
        "material.io",
        "math-cs.gordon.edu",
        "math-linux.com",
        "math.cmu.edu",
        "math.nsc.ru",
        "math.temple.edu",
        "mathbits.com",
        "mathopenref.com",
        "mathpapa.com",
        "mathsisfun.com",
        "mathwords.com",
        "maxi-pedia.com",
        "maya.vc",
        "mbmlbook.com",
        "mbsdirect.com",
        "measurethat.net",
        "med.stanford.edu",
        "mediaplayer10.com",
        "medicalbiostatistics.com",
        "messenger.com",
        "metabase.com",
        "mhacks.org",
        "mikulskibartosz.name",
        "militarycac.com",
        "milwaukeetool.com",
        "minecraft.net",
        "modelzoo.co",
        "molbiotools.com",
        "monkeytype.com",
        "montgomerycountymd.gov",
        "moonbooks.org",
        "mordorintelligence.com",
        "movable-type.co.uk",
        "mtch.com",
        "mtsu.edu",
        "multipath-tcp.org",
        "mundanecode.com",
        "mutualfunds.com",
        "mux.com",
        "myaccountviewonline.com",
        "myanimelist.net",
        "mybookmarks.com",
        "mybyways.com",
        "mycamra.com",
        "myfavoritestoolbar.net",
        "myflix.pk",
        "mylife.com",
        "mystore411.com",
        "nami.org",
        "nature.com",
        "navicat.com",
        "needtags.com",
        "neevia.com",
        "net-informations.com",
        "netmarketshare.com",
        "networksorcery.com",
        "newlook.dteenergy.com",
        "nexthop.com.au",
        "nghttp2.org",
        "nicadd.niu.edu",
        "nivas.hr",
        "nj.gov",
        "njcourts.gov",
        "nobadmemories.com",
        "normatecrecovery.com",
        "noteburner.com",
        "noterepeat.com",
        "nsf.gov",
        "nssurge.com",
        "number2word.com",
        "numbertheory.org",
        "numpy.org",
        "oag.ca.gov",
        "office.live.com",
        "officeoneonline.com",
        "oklahoman.com",
        "omim.org",
        "omniglot.com",
        "ongres.com",
        "online-toolz.com",
        "onlinelibrary.wiley.com",
        "onlinestatbook.com",
        "opcdatahub.com",
        "openbookproject.net",
        "opencamera.org.uk",
        "openmymind.net",
        "opensemanticsearch.org",
        "opentechguides.com",
        "openzim.org",
        "opinionatedgeek.com",
        "opussoftware.com",
        "orau.gov",
        "orioniconlibrary.com",
        "osi-model.com",
        "osquery.io",
        "osta.org",
        "outlookonthedesktop.com",
        "overlay-tech.com",
        "p-nand-q.com",
        "pacificcontrols.net",
        "pacificresearchplatform.org",
        "packetfabric.com",
        "pagetutor.com",
        "pamela.biz",
        "panic.com",
        "paperswithcode.com",
        "pastebin.pl",
        "paulirish.com",
        "paulund.co.uk",
        "paulwhippconsulting.com",
        "percentage-change-calculator.com",
        "perceptualedge.com",
        "permadi.com",
        "persistiq.com",
        "peter-hoffmann.com",
        "phanderson.com",
        "phonespell.org",
        "phoronix.com",
        "physics.princeton.edu",
        "piware.de",
        "planetmath.org",
        "planetpython.org",
        "plants.usda.gov",
        "platt.com",
        "playdeck.net",
        "pocketsoap.com",
        "polymorphe.org",
        "ports1961.com",
        "postgis.net",
        "postgresguide.com",
        "ppp.uiuc.edu",
        "practicalcryptography.com",
        "printuniversal.com",
        "probuilds.net",
        "processing.org",
        "programata.bg",
        "programmersought.com",
        "programming-idioms.org",
        "psharvard.org",
        "publichealth.lacounty.gov",
        "pylint.org",
        "pyqtgraph.org",
        "python-ds.com",
        "python-future.org",
        "python.omics.wiki",
        "pythonprogramming.net",
        "qcad.org",
        "quadibloc.com",
        "quadtonerip.com",
        "quantilus.com",
        "quintagroup.com",
        "quirksmode.org",
        "quora.com",
        "rau-deaver.org",
        "razorsql.com",
        "rd-alliance.org",
        "react-hook-form.com",
        "reactenlightenment.com",
        "reactnative.com",
        "readabilityformulas.com",
        "rebol.com",
        "recordnotfound.com",
        "redislabs.com",
        "reederapp.com",
        "refreshyourcache.com",
        "regexlib.com",
        "remapkey.com",
        "research.ibm.com",
        "reset.build",
        "restapitutorial.com",
        "retool.com",
        "rhymezone.com",
        "ribice.ba",
        "rion.io",
        "riot.im",
        "rob-mcculloch.org",
        "rosettacode.org",
        "rotatinghome.com",
        "router-switch.com",
        "roytuts.com",
        "royvanrijn.com",
        "rpubs.com",
        "rrwebfetch.com",
        "ruby-china.org",
        "rubydoc.info",
        "ruger.com",
        "runestone.academy",
        "safegraph.com",
        "salesforcetutorial.com",
        "sankeymatic.com",
        "sapbazar.com",
        "saptechnical.com",
        "sascha-frank.com",
        "sassnet.com",
        "sbarjatiya.com",
        "sbof.com",
        "sc.edu",
        "scala-lang.org",
        "scalelab.com",
        "scalyr.com",
        "scantips.com",
        "schedmd.com",
        "schellscenic.com",
        "scipy.org",
        "scott.plus",
        "screen-size.info",
        "sctoolcorp.com",
        "secureteen.com",
        "self.gutenberg.org",
        "semantic-kitti.org",
        "sequelpro.com",
        "serversmtp.com",
        "sfsuperiorcourt.org",
        "shoelace.io",
        "shotcut.org",
        "shrm.org",
        "shrubbery.net",
        "sidebranch.com",
        "signal.org",
        "simpragma.com",
        "sinclair.edu",
        "sites.google.com",
        "sken.io",
        "sketchingwithcss.com",
        "skillcrush.com",
        "sltrib.com",
        "smallcultfollowing.com",
        "smallsurething.com",
        "snorkel.ai",
        "softschools.com",
        "soundswitch.com",
        "sourcedaddy.com",
        "sourceware.org",
        "spblog.net",
        "specialtyproduce.com",
        "spectrumbusiness.net",
        "spreadsheet1.com",
        "sqlines.com",
        "sqlite.org",
        "sqlmatters.com",
        "sqlusa.com",
        "stackabuse.com",
        "stackshare.io",
        "stahlworks.com",
        "stardewvalleywiki.com",
        "startupleadership.com",
        "startx.com",
        "stateofopendata.od4d.net",
        "stateparks.com",
        "statlect.com",
        "statpower.net",
        "stefan.buettcher.org",
        "stepzen.com",
        "stilltasty.com",
        "stormotion.io",
        "strftime.net",
        "structurely.com",
        "styled-components.com",
        "sumopaint.com",
        "support.cc.gatech.edu",
        "support.earthlink.net",
        "support.hp.com",
        "survivalservers.com",
        "swmath.org",
        "tableizer.journalistopia.com",
        "tabulator.info",
        "tailscale.com",
        "taskworld.com",
        "tcl.tk",
        "teacherzone.com",
        "techbrood.com",
        "techdatacloud.eu",
        "techmeme.com",
        "telematika.org",
        "temporal.io",
        "texdoc.net",
        "textem.net",
        "tfidf.com",
        "tfsbillpay.com",
        "thebitguru.com",
        "thecinemaholic.com",
        "thefouriertransform.com",
        "thegamesjournal.com",
        "theinfatuation.com",
        "theoatmeal.com",
        "theoutbound.com",
        "thepattern.com",
        "thesassway.com",
        "theweek.com",
        "thexlab.com",
        "thinkingwithaline.com",
        "thomas-cokelaer.info",
        "tidelift.com",
        "tigercolor.com",
        "time-time.net",
        "time.gov",
        "timebie.com",
        "timestampconvert.com",
        "tizag.com",
        "tomveatch.com",
        "tracktherecovery.org",
        "trankynam.com",
        "trustedcomputinggroup.org",
        "tug.org",
        "turncameraon.com",
        "tutanota.com",
        "tutorialkart.com",
        "twc.texas.gov",
        "ubackup.com",
        "ubiqx.org",
        "ucet.org",
        "udates.com",
        "uh.edu",
        "uhcl.edu",
        "ui.nv.gov",
        "ultralinux.org",
        "umich.edu",
        "umkc.edu",
        "unicode.org",
        "uninstallmacapp.com",
        "unitronicsplc.com",
        "universalclass.com",
        "unixwiz.net",
        "unknownroad.com",
        "unraid.net",
        "update.microsoft.com",
        "usaco.org",
        "usacocoach.com",
        "usalearns.org",
        "useragentstring.com",
        "uservoice.com",
        "usg.edu",
        "usmle.org",
        "utdallas.edu",
        "utf8-chartable.de",
        "valgrind.org",
        "vassarstats.net",
        "vecta.io",
        "verilog.renerta.com",
        "vertabelo.com",
        "vfsforgit.org",
        "virtualmin.com",
        "visuallink.com",
        "vizito.be",
        "voyteklab.com",
        "w3resource.com",
        "walterfootball.com",
        "warecentral.com",
        "warren-selbert.com",
        "watchful.io",
        "way2tutorial.com",
        "wdwinfo.com",
        "wealthobjects.com",
        "weatherstreet.com",
        "webdataextractionservices.com",
        "webmath.com",
        "webmin.com",
        "webscraper.io",
        "webstyleguide.com",
        "weknowinc.com",
        "wi-fi.org",
        "wickedlysmart.com",
        "wickham43.net",
        "williamyaoh.com",
        "windstream.com",
        "wingdb.com",
        "winged.ch",
        "winginx.com",
        "wordcount.com",
        "workflow.is",
        "worldclim.org",
        "worldofleveldesign.com",
        "wowgold.hk",
        "wowinterface.com",
        "wpowerproducts.com",
        "writebetteremails.com",
        "wsdot.wa.gov",
        "x-rates.com",
        "xahlee.info",
        "xcprod.com",
        "xe.com",
        "xignite.com",
        "xmlgrid.net",
        "xmpp.net",
        "xor.pw",
        "xspdf.com",
        "yourcoach.be",
        "zagat.com",
        "zapatopi.net",
        "zencephalon.com",
        "zim-wiki.org",
        "zinstall.com",
        "zipmap.net",
        "zlib.net",
        "zmenu.com",
        "zoneminder.com",
        "zvon.org",
    ]

    private static let domainToLowerPath: Set<String> = [
        "247sports.com",
        "3cx.com",
        "8notes.com",
        "8onthepark.com",
        "a-z-animals.com",
        "aao.org",
        "abbreviations.com",
        "abc.virginia.gov",
        "abcam.com",
        "abebooks.com",
        "acc.org",
        "accenture.com",
        "access.redhat.com",
        "accessdata.fda.gov",
        "account.live.com",
        "accounts.google.com",
        "acefitness.org",
        "acehardware.com",
        "achieve.lausd.net",
        "acog.org",
        "acronymfinder.com",
        "acronyms.thefreedictionary.com",
        "active.com",
        "adoptapet.com",
        "ads.google.com",
        "adt.com",
        "af.mil",
        "agingcare.com",
        "ahajournals.org",
        "aicpa.org",
        "airforcemag.com",
        "airnav.com",
        "ajronline.org",
        "alaskaair.com",
        "allaboutbirds.org",
        "alleywatch.com",
        "almanac.com",
        "altaro.com",
        "altova.com",
        "alz.org",
        "amazon.com",
        "amd.com",
        "americanexpress.com",
        "amfam.com",
        "ams.usda.gov",
        "anaconda.org",
        "analog.com",
        "answers.acrobatusers.com",
        "ansys.com",
        "anthem.com",
        "any.do",
        "aopa.org",
        "api.jquery.com",
        "apidock.com",
        "app.leg.wa.gov",
        "appliancesconnection.com",
        "applitrack.com",
        "aqua-calc.com",
        "ar15.com",
        "arborday.org",
        "archdaily.com",
        "arduino.cc",
        "ark-funds.com",
        "army.mil",
        "armypubs.army.mil",
        "artistsnetwork.com",
        "artstation.com",
        "ascd.org",
        "asha.org",
        "ask.slashdot.org",
        "assessor.co.la.ca.us",
        "assets.hcca-info.org",
        "asus.com",
        "athletic.net",
        "atom.io",
        "atptour.com",
        "atriumhealth.org",
        "austintexas.org",
        "autoanything.com",
        "autotrader.com",
        "avery.com",
        "aviewfrommyseat.com",
        "aws.org",
        "azaleabarcodes.com",
        "azdor.gov",
        "azdot.gov",
        "babynames.com",
        "babynamewizard.com",
        "backmarket.com",
        "ballarddesigns.com",
        "bank-code.net",
        "batteriesplus.com",
        "behance.net",
        "belkin.com",
        "benefits.gov",
        "benjaminmoore.com",
        "bergdorfgoodman.com",
        "bestcase.com",
        "betterhealth.vic.gov.au",
        "bettycrocker.com",
        "bevnet.com",
        "bible.com",
        "bible.knowing-jesus.com",
        "bibme.org",
        "big5sportinggoods.com",
        "biggerpockets.com",
        "biglots.com",
        "billtrack50.com",
        "binance.com",
        "bisnow.com",
        "bizbuysell.com",
        "bl.ocks.org",
        "blackwasp.co.uk",
        "blockchain.com",
        "blocksite.co",
        "blog.csdn.net",
        "blog.hootsuite.com",
        "blog.hubspot.com",
        "blog.mozilla.org",
        "blogs.bing.com",
        "blogs.oracle.com",
        "bls.gov",
        "blueshieldca.com",
        "bluestoneperennials.com",
        "boattrader.com",
        "bogleheads.org",
        "bookbrowse.com",
        "bookdepository.com",
        "brickset.com",
        "brightcomputing.com",
        "britishairways.com",
        "brokercheck.finra.org",
        "brother-usa.com",
        "brownells.com",
        "budsgunshop.com",
        "bulbapedia.bulbagarden.net",
        "businessinsider.in",
        "businessnamegenerator.com",
        "buy.garmin.com",
        "c-sharpcorner.com",
        "caesars.com",
        "calbar.ca.gov",
        "calendar-12.com",
        "callofduty.com",
        "calrecycle.ca.gov",
        "canr.msu.edu",
        "capitalgroup.com",
        "carbonhealth.com",
        "cardgames.app",
        "carecredit.com",
        "careeronestop.org",
        "cash.app",
        "catalog.hardydiagnostics.com",
        "cde.ca.gov",
        "cdn.ymaws.com",
        "cdph.ca.gov",
        "cdss.ca.gov",
        "cdw.com",
        "cedargraphicsinc.com",
        "cedarville.edu",
        "century21.com",
        "cesarsway.com",
        "cga.ct.gov",
        "chabad.org",
        "champion.gg",
        "channel4.com",
        "channel9.msdn.com",
        "chatsports.com",
        "cheapflights.com",
        "chemicalbook.com",
        "chemocare.com",
        "chicagobooth.edu",
        "chicagomag.com",
        "choosechicago.com",
        "chortle.ccsu.edu",
        "chp.ca.gov",
        "christies.com",
        "cia.gov",
        "cibmtr.org",
        "cincinnatichildrens.org",
        "cis.temple.edu",
        "cityofberkeley.info",
        "cityofsacramento.org",
        "ck12.org",
        "cleartax.in",
        "clickondetroit.com",
        "cmich.edu",
        "cms.gov",
        "code.visualstudio.com",
        "codedaily.io",
        "codefresh.io",
        "codeproject.com",
        "coecsl.ece.illinois.edu",
        "coinmarketcap.com",
        "coinsutra.com",
        "collab.its.virginia.edu",
        "columbus.gov",
        "community.adobe.com",
        "community.chocolatey.org",
        "community.hpe.com",
        "community.windows.com",
        "compellingtruth.org",
        "comptroller.texas.gov",
        "conceptcarz.com",
        "conjugator.reverso.net",
        "consumercellular.com",
        "content.techgig.com",
        "context.reverso.net",
        "controller.com",
        "costco.com",
        "costcobusinessdelivery.com",
        "costcotravel.com",
        "courts.state.va.us",
        "covers.com",
        "cpuc.ca.gov",
        "crateandbarrel.com",
        "creately.com",
        "cricbuzz.com",
        "criswellchryslerjeepdodge.com",
        "crossword-solver.io",
        "crucial.com",
        "crwflags.com",
        "cs.cornell.edu",
        "csis.ul.ie",
        "csrc.nist.gov",
        "csus.edu",
        "csusm.edu",
        "ctimls.com",
        "currency-converter-calculator.com",
        "curseforge.com",
        "cutepdf.com",
        "cwiki.apache.org",
        "d.comenity.net",
        "dallascityhall.com",
        "data.worldbank.org",
        "datetime360.com",
        "db-engines.com",
        "defense.gov",
        "definitions.net",
        "delawareinc.com",
        "dell.com",
        "denvergov.org",
        "depts.ttu.edu",
        "developer.amazon.com",
        "developer.apple.com",
        "developer.ebay.com",
        "developer.mozilla.org",
        "developer.nvidia.com",
        "developers.exlibrisgroup.com",
        "deviantart.com",
        "dfas.mil",
        "dhcs.ca.gov",
        "dhs.state.il.us",
        "dice.com",
        "dict.hinkhoj.com",
        "digitalcommerce360.com",
        "dignityhealth.org",
        "dir.ca.gov",
        "discord.com",
        "discounttire.com",
        "disneyland.disney.go.com",
        "disneyworld.disney.go.com",
        "dispatch.com",
        "distrowatch.com",
        "diys.com",
        "dla.mil",
        "dmarcanalyzer.com",
        "dnr.wi.gov",
        "doc.qt.io",
        "docs.actian.com",
        "docs.microsoft.com",
        "docs.splunk.com",
        "documentation.solarwinds.com",
        "dogster.com",
        "dogtrekker.com",
        "doh.sd.gov",
        "doh.wa.gov",
        "dol.gov",
        "dollar.com",
        "dollartree.com",
        "downdetector.com",
        "download.autodesk.com",
        "dps.texas.gov",
        "dribbble.com",
        "drivers.softpedia.com",
        "driversed.com",
        "dsw.com",
        "duke-energy.com",
        "dupontregistry.com",
        "earthobservatory.nasa.gov",
        "ebi.ac.uk",
        "ebridgeconnections.com",
        "economictimes.indiatimes.com",
        "ed.gov",
        "edd.ca.gov",
        "edhrec.com",
        "editorial.rottentomatoes.com",
        "efile.com",
        "eguruchela.com",
        "eia.gov",
        "elsevier.com",
        "emerald.com",
        "emergeinteractive.com",
        "emerson.com",
        "emirates.com",
        "en.bitcoin.it",
        "en.bitcoinwiki.org",
        "en.help.roblox.com",
        "en.wikibooks.org",
        "en.wikipedia.org",
        "en.wiktionary.org",
        "energystar.gov",
        "engineering.com",
        "engineering.purdue.edu",
        "entnemdept.ufl.edu",
        "epguides.com",
        "equifax.com",
        "es.wikipedia.org",
        "esv.org",
        "etherscan.io",
        "etrailer.com",
        "etymonline.com",
        "europepmc.org",
        "evga.com",
        "ewg.org",
        "exploratorium.edu",
        "extension.iastate.edu",
        "faa.gov",
        "facebook.com",
        "fairfaxcounty.gov",
        "familytreemagazine.com",
        "famousfootwear.com",
        "fandangonow.com",
        "fao.org",
        "farfetch.com",
        "fast-growing-trees.com",
        "fdic.gov",
        "federalreserve.gov",
        "ferris.edu",
        "file-intelligence.comodo.com",
        "fileformat.info",
        "finalsitesupport.com",
        "finance.yahoo.com",
        "financhill.com",
        "financial-dictionary.thefreedictionary.com",
        "findagrave.com",
        "finewoodworking.com",
        "finishline.com",
        "finra.org",
        "fishersci.com",
        "flightradar24.com",
        "flightstats.com",
        "flightview.com",
        "flixed.io",
        "flooranddecor.com",
        "floridastateparks.org",
        "fmsinc.com",
        "fontspace.com",
        "fontsquirrel.com",
        "forever21.com",
        "forgetcode.com",
        "forsalebyowner.com",
        "fox2now.com",
        "fred.stlouisfed.org",
        "freelancer.com",
        "frontier.com",
        "ftb.ca.gov",
        "fueleconomy.gov",
        "funtrivia.com",
        "fws.gov",
        "fxstreet.com",
        "gadgetsnow.com",
        "gao.gov",
        "gatherer.wizards.com",
        "gearbest.com",
        "genome.ucsc.edu",
        "geo.craigslist.org",
        "geokov.com",
        "getroost.zendesk.com",
        "gettyimages.com",
        "gfycat.com",
        "gifts.com",
        "gismaps.kingcounty.gov",
        "gist.github.com",
        "github.blog",
        "github.com",
        "gitter.im",
        "glassdoor.com",
        "globalair.com",
        "gohugo.io",
        "governing.com",
        "governmentjobs.com",
        "govtech.com",
        "grammarbook.com",
        "grants.nih.gov",
        "grc.nasa.gov",
        "greatergood.berkeley.edu",
        "greentechmedia.com",
        "grok.lsu.edu",
        "guns.com",
        "gunsamerica.com",
        "gurufocus.com",
        "haas.berkeley.edu",
        "hagerty.com",
        "hallmark.com",
        "har.com",
        "harborfreight.com",
        "hawaiianairlines.com",
        "hbs.edu",
        "health.harvard.edu",
        "health.ucsd.edu",
        "healthcare.ascension.org",
        "healthcare.gov",
        "healthy.kaiserpermanente.org",
        "healthychildren.org",
        "help.aweber.com",
        "help.calendly.com",
        "help.dreamhost.com",
        "help.figma.com",
        "help.hbomax.com",
        "help.hotjar.com",
        "help.minecraft.net",
        "help.nytimes.com",
        "help.parsehub.com",
        "help.zearn.org",
        "helpcenter.steinberg.de",
        "hendrix.edu",
        "higheredjobs.com",
        "hipaaspace.com",
        "hltv.org",
        "hme-business.com",
        "hmhbooks.com",
        "homedit.com",
        "hopkinsmedicine.org",
        "hostsearch.com",
        "houseofnames.com",
        "houstonisd.org",
        "howardhanna.com",
        "howtogeek.com",
        "hrc.org",
        "htmlgoodies.com",
        "hud.gov",
        "huduser.gov",
        "humana.com",
        "huntington.com",
        "hy-vee.com",
        "icewalkers.com",
        "icicibank.com",
        "iconarchive.com",
        "icons8.com",
        "identitytheft.gov",
        "iep.online-iep.com",
        "iep.utm.edu",
        "iherb.com",
        "ilga.gov",
        "imf.org",
        "imslp.org",
        "in.finance.yahoo.com",
        "indeed.com",
        "inflectra.com",
        "infoq.com",
        "institutionalinvestor.com",
        "internet-ink.com",
        "investor.vanguard.com",
        "investorshub.advfn.com",
        "investorsobserver.com",
        "iphonehacks.com",
        "iristech.co",
        "isc2.org",
        "isitdownrightnow.com",
        "jabra.com",
        "jacksonville.com",
        "jaksta.com",
        "jameco.com",
        "jasinskionline.com",
        "jdpower.com",
        "jea.com",
        "joebiden.com",
        "jotform.com",
        "journals.lww.com",
        "jpost.com",
        "jwpepper.com",
        "kb.intermedia.net",
        "kb.mit.edu",
        "kb.netgear.com",
        "keepitsafe.com",
        "kellogg.northwestern.edu",
        "khwiki.com",
        "kidney.org",
        "kids.britannica.com",
        "kite.com",
        "klwines.com",
        "knowledge.autodesk.com",
        "knowledge.hubspot.com",
        "kongregate.com",
        "kryteriononline.com",
        "kycourts.gov",
        "kylesconverter.com",
        "landsofamerica.com",
        "larksuite.com",
        "law2.umkc.edu",
        "lawdepot.com",
        "lcps.org",
        "learn.saylor.org",
        "learnopengl.com",
        "leetcode.com",
        "leg.state.nv.us",
        "legal-dictionary.thefreedictionary.com",
        "legis.state.pa.us",
        "lenscrafters.com",
        "lexisnexis.com",
        "libguides.library.kent.edu",
        "lichess.org",
        "lifehack.org",
        "linkedin.com",
        "linux.com",
        "linuxconfig.org",
        "linuxfoundation.org",
        "literarydevices.net",
        "livenation.com",
        "localcabledeals.com",
        "ltcconline.net",
        "ludwig.guru",
        "lw.com",
        "lyft.com",
        "lynda.com",
        "machinio.com",
        "macmost.com",
        "macobserver.com",
        "macroaxis.com",
        "macrumors.com",
        "macstories.net",
        "mail.google.com",
        "makemytrip.com",
        "makeschool.com",
        "makeupalley.com",
        "malegislature.gov",
        "mamanatural.com",
        "marcustheatres.com",
        "maricopa.gov",
        "mariowiki.com",
        "marketplace.xbox.com",
        "marketwatch.com",
        "massgeneral.org",
        "mastercook.com",
        "masterofmalt.com",
        "mathcentral.uregina.ca",
        "mayoclinic.org",
        "mbusa.com",
        "mckinsey.com",
        "mcmaster.com",
        "med.umich.edu",
        "med.unc.edu",
        "mediawiki.org",
        "medical-dictionary.thefreedictionary.com",
        "medicare.gov",
        "megamillions.com",
        "memedroid.com",
        "merriam-webster.com",
        "merrilledge.com",
        "metal-archives.com",
        "methods.sagepub.com",
        "metopera.org",
        "microcenter.com",
        "microsoft.com",
        "mindtools.com",
        "minecraft.fandom.com",
        "missionlocal.org",
        "mkyong.com",
        "mobilelinkgen.zendesk.com",
        "models.com",
        "mondaq.com",
        "monoprice.com",
        "monster.com",
        "montgomerycountymd.gov",
        "moodys.com",
        "morganlewis.com",
        "morningstar.com",
        "mouser.com",
        "msi.com",
        "msn.com",
        "msnbc.com",
        "muscleandstrength.com",
        "mxtoolbox.com",
        "my.napier.ac.uk",
        "myanimelist.net",
        "myfloridacfo.com",
        "myhealth.alberta.ca",
        "mylifetime.zendesk.com",
        "myweather2.com",
        "n.rivals.com",
        "na.op.gg",
        "nadaguides.com",
        "name.com",
        "namecheap.com",
        "nami.org",
        "nashville.gov",
        "nationalgridus.com",
        "nb.fidelity.com",
        "nbcnews.com",
        "nces.ed.gov",
        "ncsl.org",
        "needtags.com",
        "nejm.org",
        "netflix.com",
        "netgear.com",
        "netspotapp.com",
        "newbalance.com",
        "newegg.com",
        "news.gallup.com",
        "news.microsoft.com",
        "newschool.edu",
        "newworldencyclopedia.org",
        "nga.org",
        "nglish.com",
        "niceonecode.com",
        "nike.com",
        "nikonusa.com",
        "ninds.nih.gov",
        "niu.edu",
        "npm.io",
        "npmjs.com",
        "nucleus.iaea.org",
        "nurse.org",
        "nvidia.com",
        "nwf.org",
        "nysenate.gov",
        "nytco.com",
        "obamawhitehouse.archives.gov",
        "ods.od.nih.gov",
        "offensive-security.com",
        "office.live.com",
        "ohchr.org",
        "oldschool.runescape.wiki",
        "olt.com",
        "onenote.com",
        "oodlestechnologies.com",
        "opm.gov",
        "optimum.net",
        "oregon.gov",
        "oreillyauto.com",
        "orvis.com",
        "osha.gov",
        "outlook.live.com",
        "outsystems.com",
        "overleaf.com",
        "overstock.com",
        "paganresearch.io",
        "panjiva.com",
        "parallels.com",
        "parks.ca.gov",
        "passportsandvisas.com",
        "patient.info",
        "paxful.com",
        "paypal.com",
        "pcoservices.zendesk.com",
        "pe.usps.com",
        "peacehealth.org",
        "pearsonsupport.helpserve.com",
        "penpublishing.com",
        "peoplekeep.com",
        "perfectgame.org",
        "petersons.com",
        "pexels.com",
        "pfaf.org",
        "pga.com",
        "phila.gov",
        "philpapers.org",
        "phoenix.gov",
        "phrogz.net",
        "physicsclassroom.com",
        "physio-pedia.com",
        "pkg.go.dev",
        "plannedparenthood.org",
        "plasticsurgery.org",
        "player.fm",
        "playstationtrophies.org",
        "plugins.jetbrains.com",
        "podbean.com",
        "police1.com",
        "porsche.com",
        "portal.ct.gov",
        "portswigger.net",
        "poshmark.com",
        "postofficeshours.com",
        "poundsterlinglive.com",
        "practicalecommerce.com",
        "predictiveanalyticstoday.com",
        "premierleague.com",
        "priceintelligently.com",
        "privacy.microsoft.com",
        "probuilds.net",
        "process.st",
        "productschool.com",
        "protocol.com",
        "providence.org",
        "providencejournal.com",
        "prowritingaid.com",
        "proz.com",
        "psacard.com",
        "pubchem.ncbi.nlm.nih.gov",
        "public.com",
        "public.navy.mil",
        "publichealth.lacounty.gov",
        "pythontic.com",
        "quotes.net",
        "racefans.net",
        "radiologyinfo.org",
        "rapidapi.com",
        "rationalwiki.org",
        "raymondjames.com",
        "rcsb.org",
        "redmondmag.com",
        "reference.codeproject.com",
        "regions.com",
        "renaissancecapital.com",
        "renewalbyandersen.com",
        "rentalcars.com",
        "rentals.com",
        "repairclinic.com",
        "repl.it",
        "reservations.com",
        "resources.esri.com",
        "resources.sei.cmu.edu",
        "revenue.wi.gov",
        "reviews.io",
        "rhs.org.uk",
        "riteaid.com",
        "robertsspaceindustries.com",
        "robinhood.com",
        "roblox.com",
        "rochester.edu",
        "ronsplace.eu",
        "rosettacode.org",
        "rsc.org",
        "runescape.wiki",
        "runningwarehouse.com",
        "rv.campingworld.com",
        "rvt.com",
        "rvusa.com",
        "sajeconsultants.com",
        "salliemae.com",
        "santanderbank.com",
        "sba.com",
        "sccgov.org",
        "scdhec.gov",
        "scholarships.com",
        "schools.nyc.gov",
        "schwab.wallst.com",
        "sciencebuddies.org",
        "sciencenewsforstudents.org",
        "scipy.github.io",
        "scouting.org",
        "searchengineland.com",
        "seattle.gov",
        "seattlechildrens.org",
        "seattlepi.com",
        "secure.n-able.com",
        "self.gutenberg.org",
        "services.flhsmv.gov",
        "sfdph.org",
        "sfgov.org",
        "sfmoma.org",
        "sfrecpark.org",
        "shift.newco.co",
        "ship24.com",
        "shop.lululemon.com",
        "shopbop.com",
        "shrm.org",
        "shutterstock.com",
        "si.edu",
        "sim-unlock.net",
        "simpleindex.com",
        "simplethread.com",
        "sixflags.com",
        "skybrary.aero",
        "slack.com",
        "slang.org",
        "smu.edu",
        "socialblade.com",
        "sodapdf.com",
        "softwaredaily.com",
        "sophos.com",
        "soundcloud.com",
        "specialized.com",
        "speedrun.com",
        "sphweb.bumc.bu.edu",
        "sportslogos.net",
        "sportsmansoutdoorsuperstore.com",
        "ssa.gov",
        "stackoverflow.com",
        "stagraph.com",
        "stardewvalleywiki.com",
        "starsunfolded.com",
        "startingyourbusiness.com",
        "starwars.com",
        "statefarm.com",
        "stevefenton.co.uk",
        "stilltasty.com",
        "stlouis-mo.gov",
        "stock.adobe.com",
        "stocknews.com",
        "stockrow.com",
        "stocktwits.com",
        "streamlabs.com",
        "summitracing.com",
        "sunrisesunset.com",
        "supermicro.com",
        "supplychain247.com",
        "support.3dcart.com",
        "support.airtable.com",
        "support.apple.com",
        "support.appsflyer.com",
        "support.befunky.com",
        "support.bell.ca",
        "support.bitly.com",
        "support.discord.com",
        "support.gusto.com",
        "support.hp.com",
        "support.knowbe4.com",
        "support.kraken.com",
        "support.lenovo.com",
        "support.motorola.com",
        "support.netdocuments.com",
        "support.onepeloton.com",
        "support.ring.com",
        "support.roku.com",
        "support.shippingeasy.com",
        "support.shotgunsoftware.com",
        "support.shutterfly.com",
        "support.skype.com",
        "support.spotify.com",
        "support.squarespace.com",
        "support.stackpath.com",
        "support.strava.com",
        "support.taxslayer.com",
        "support.taxslayerpro.com",
        "support.techsmith.com",
        "support.ti.davidson.edu",
        "support.twilio.com",
        "support.ubisoft.com",
        "support.zendesk.com",
        "support.zoom.us",
        "supportcenter.devexpress.com",
        "supremecourt.gov",
        "synonyms.com",
        "t-mobile.com",
        "t.me",
        "tailorbrands.com",
        "tarladalal.com",
        "taxact.com",
        "taxpolicycenter.org",
        "tdwi.org",
        "teamusa.org",
        "techgenix.com",
        "techsoup.org",
        "telegram.com",
        "templates.office.com",
        "tennis-warehouse.com",
        "tensorflow.org",
        "tesla.com",
        "theamericancollege.edu",
        "thegazette.com",
        "thehustle.co",
        "theinformation.com",
        "themoneyconverter.com",
        "therealreal.com",
        "thingiverse.com",
        "thriftbooks.com",
        "ti.com",
        "tiaa.org",
        "ticketmaster.com",
        "tidal.com",
        "tileteam.zendesk.com",
        "time.is",
        "tldrlegal.com",
        "toasttab.com",
        "tourtexas.com",
        "toyota.com",
        "toywiz.com",
        "tp-link.com",
        "tractorsupply.com",
        "traderjoes.com",
        "translatorscafe.com",
        "transportnsw.info",
        "travel.usnews.com",
        "travelawaits.com",
        "travelchinaguide.com",
        "travelok.com",
        "treasury.gov",
        "treasurydirect.gov",
        "trekbikes.com",
        "trendmicro.com",
        "tributearchive.com",
        "tripplite.com",
        "tutorial.math.lamar.edu",
        "tutorialdost.com",
        "tutorialsteacher.com",
        "tvtropes.org",
        "twitch.tv",
        "twitter.com",
        "uaex.edu",
        "ucanr.edu",
        "uclahealth.org",
        "uhaul.com",
        "uhhospitals.org",
        "uk.finance.yahoo.com",
        "uline.com",
        "uml.edu",
        "un.org",
        "uncw.edu",
        "underwaterphotography.com",
        "united.com",
        "unitypoint.org",
        "unix.com",
        "uphe.com",
        "upmc.com",
        "ups.com",
        "urban.org",
        "us.kohler.com",
        "usa.canon.com",
        "usa.gov",
        "usajobs.gov",
        "usermanual.wiki",
        "ushistory.org",
        "va.gov",
        "virginia.org",
        "virginiamason.org",
        "visaprepaidprocessing.com",
        "visitorlando.com",
        "visitutah.com",
        "visualstudiomagazine.com",
        "vitacost.com",
        "vocabulary.com",
        "vudu.com",
        "w3.org",
        "w3schools.com",
        "walgreens.com",
        "walmart.com",
        "walterfootball.com",
        "washington.org",
        "wattpad.com",
        "way.com",
        "wdwinfo.com",
        "wearedevs.net",
        "weather-and-climate.com",
        "weather.gov",
        "web.mit.edu",
        "weber.com",
        "webflow.com",
        "weblog.west-wind.com",
        "webpages.uidaho.edu",
        "webqc.org",
        "website.com",
        "webster-dictionary.org",
        "wellesley.edu",
        "wellsfargo.com",
        "wesm.github.io",
        "westernunion.com",
        "wh40k.lexicanum.com",
        "whatbox.ca",
        "whitman.edu",
        "whitney.org",
        "who.int",
        "wickedlocal.com",
        "wiki.archlinux.org",
        "wiki.factorio.com",
        "wiki.openstreetmap.org",
        "wiki.python.org",
        "wiki.vyos.net",
        "wikitravel.org",
        "wikitree.com",
        "wikizero.com",
        "wildlife.ca.gov",
        "wilsonbrosgardens.com",
        "winespectator.com",
        "wisconsindot.gov",
        "wolterskluwer.com",
        "woocommerce.com",
        "wordplays.com",
        "worldofwarcraft.com",
        "wowwiki-archive.fandom.com",
        "wsdot.com",
        "wsdot.wa.gov",
        "wtae.com",
        "wtatennis.com",
        "wwnorton.com",
        "www1.maths.leeds.ac.uk",
        "www1.nationalgridus.com",
        "www1.salary.com",
        "www2.advantech.com",
        "www2.calstate.edu",
        "www2.chemistry.msu.edu",
        "www2.illinois.gov",
        "www3.nd.edu",
        "www3.ntu.edu.sg",
        "www8.hp.com",
        "wwwnc.cdc.gov",
        "wyzant.com",
        "xbox.com",
        "xboxachievements.com",
        "youglish.com",
        "yourtango.com",
        "zamzar.com",
        "zeenews.india.com",
        "zoominfo.com",
        "zumiez.com",
    ]
}
