# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
    app_store_connect_api_key
    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'Certificates.p12',
      certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
    )
  end
  desc "Description of what the lane does"
  lane :build_and_deploy do
    # build_app(
    #   configuration: "Release",
    #   scheme: "Client",
    #   clean: true,
    #   export_options: "./Scripts/ExportOptions.plist"
    # )
    # upload_to_testflight(
    #   changelog: "Internal Test Build",
    #   groups: ["Friends and family",
    #             "Apple Review",
    #             "Neevans (employees only)"]
    # )
    version_str = File.open("../Client/AppConfig.xcconfig").grep(/BROWSER_MARKETING_VERSION = /)
    marketing_version = (version_str[0].to_s.split)[2]
    build_number_str = File.open("../Client/AppConfig.xcconfig").grep(/BROWSER_PROJECT_VERSION = /)
    build_number = (build_number_str[0].to_s.split)[2]
     slack(
       message: ":fruitcompany: Uploaded Build ##{build_number} (v#{marketing_version}) to App Store\n\n\n <https://appstoreconnect.apple.com/apps/1543288638/testflight/ios/|App Store TestFlight>",
       default_payloads: [],
       slack_url: ENV["SLACK_URL"]
     )
  end
end
