# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Run daily build script
        run: |
          git checkout chung/reviewer
          gh pr create -t "Test PR" -r "ios" -b "Test PR"
          if [ "$?" -ne 0 ]; then
            echo "build script failure. Aborting..."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
