# This is a workflow for testing github action (like a github action playground)

name: Github action (for testing)

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      reviewer:
        description: 'Reviewer'
        required: false
        default: ''

jobs:
  daily-build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Run daily build script
        run: |
          ruby -r ./Scripts/build.rb -e "reviewer(\"${{ github.event.inputs.reviewer }}\")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
